# Theme & Colors
include matugen-colors.conf
# background #000000
# color8 #7c6f64
background_opacity 1


# Simulated smear effect (Kitty >= 0.37)
# cursor_trail 1
# cursor_trail_decay 0.02 0.11
# cursor_trail_start_threshold 0
#

# Cursor
cursor_shape block

# Font
font_family      JetBrains Mono Nerd Font 
italic_font      none
bold_font        auto
font_size        14
bold_font        JetBrains Mono Nerd Font  
disable_ligatures never
modify_font cell_width 0
# For Kitty >=0.32, this can simulate font-thicken
text_thickness 0.6

# Window & Padding
window_padding_width 14
window_padding_height 0
# window-padding-balance is not needed if both paddings are equal

# Shell integration
shell_integration disabled
confirm_os_window_close 0
map ctrl+shift+f search_scrollback


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
